# Generated by Django 3.2.4 on 2021-06-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propostas',
            old_name='título',
            new_name='titulo',
        ),
    ]
