# Generated by Django 3.2.4 on 2021-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_título_propostas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostas',
            name='areas_trabalho',
            field=models.TextField(default=''),
        ),
    ]
