# Generated by Django 3.2.4 on 2021-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_propostas_areas_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostas',
            name='cronologia',
            field=models.ImageField(upload_to=''),
        ),
    ]
