# Generated by Django 3.2.4 on 2021-07-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_propostas_cronologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostas',
            name='cronologia',
        ),
    ]
