# Generated by Django 3.2.4 on 2021-07-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_propostas_cronologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackorientador',
            name='orientador_id',
        ),
        migrations.RemoveField(
            model_name='notificationaluno',
            name='aluno_id',
        ),
        migrations.RemoveField(
            model_name='notificationorientador',
            name='orientador_id',
        ),
        migrations.DeleteModel(
            name='FeedBackAluno',
        ),
        migrations.DeleteModel(
            name='FeedBackOrientador',
        ),
        migrations.DeleteModel(
            name='NotificationAluno',
        ),
        migrations.DeleteModel(
            name='NotificationOrientador',
        ),
    ]
